#!/bin/sh
#
# Starts uio_dmem_genirq driver
#

start() {
	echo -n "Starting uio_dmem_genirq driver: "
	insmod /lib/modules/uio_dmem_genirq.ko
	echo "OK"
}
stop() {
	echo -n "Stopping uio_dmem_genirq driver: "
	rmmod uio_dmem_genirq.ko
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

